/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R01011020928IndexRouteImport } from './routes/01011020928.index'
import { Route as R01011020928DashboardRouteImport } from './routes/01011020928.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R01011020928IndexRoute = R01011020928IndexRouteImport.update({
  id: '/01011020928/',
  path: '/01011020928/',
  getParentRoute: () => rootRouteImport,
} as any)
const R01011020928DashboardRoute = R01011020928DashboardRouteImport.update({
  id: '/01011020928/dashboard',
  path: '/01011020928/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/01011020928/dashboard': typeof R01011020928DashboardRoute
  '/01011020928/': typeof R01011020928IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/01011020928/dashboard': typeof R01011020928DashboardRoute
  '/01011020928': typeof R01011020928IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/01011020928/dashboard': typeof R01011020928DashboardRoute
  '/01011020928/': typeof R01011020928IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/01011020928/dashboard' | '/01011020928/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/01011020928/dashboard' | '/01011020928'
  id: '__root__' | '/' | '/01011020928/dashboard' | '/01011020928/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R01011020928DashboardRoute: typeof R01011020928DashboardRoute
  R01011020928IndexRoute: typeof R01011020928IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/01011020928/': {
      id: '/01011020928/'
      path: '/01011020928'
      fullPath: '/01011020928/'
      preLoaderRoute: typeof R01011020928IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/01011020928/dashboard': {
      id: '/01011020928/dashboard'
      path: '/01011020928/dashboard'
      fullPath: '/01011020928/dashboard'
      preLoaderRoute: typeof R01011020928DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R01011020928DashboardRoute: R01011020928DashboardRoute,
  R01011020928IndexRoute: R01011020928IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
